name: Publish to registry
on: 
  push:
    branch:
     -v3

jobs:
  update:
    run-on: ubuntu-latest
    steps:
    - name: Checkout
      use: actions/checkout@master

    - name: Publish to Registry
    uses: elgohr/Publish-Docker-Github-Action@master
    with:
      name: julienkeiff/docker-registry/feed_tech_server
      pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      username: ${{ secrets.DOCKER_HUB_USER }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      registry: docker.pkg.github.com
      tags: "latest,${{ env.STATE_RELEASE_VERSION }}"